language: ruby
rvm:
  - ruby-2.5.2
  - rbx
  - ruby-head
  - jruby-head

# whitelist
branches:
  only:
    - master
    - develop

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx